server:
  port: 8000

keycloak:
  realm: my_realm
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: my_client
  credentials:
    secret: 4443ee44-483a-4b0c-abc4-3b5d989791b3
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    root: info
    com.thekim12.keycloak: debug